# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GarageDoorOpener' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for GarageDoorOpener
  pod "Spark-SDK"
  pod "RNCryptor-objc", :git => "https://github.com/RNCryptor/RNCryptor-objc.git"

  target 'GarageDoorOpenerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GarageDoorOpenerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
